project:
  type: default
  output-dir: dist
  render:
    - article.qmd

format:
  jss-pdf:
    keep-tex: true
    number-sections: true
    pdf-engine: pdflatex
    journal:
      cite-shortnames: true

execute:
  echo: true
  warning: false
  message: false
  freeze: false

bibliography: manydist_refs.bib
