---
title: "manydist: spectral cluster experiments"
author: "synthetic data"
format:
  html:
    toc: true
    code-tools: true
    code-fold: true
    embed-resources: true   
execute:
  echo: true
  warning: FALSE
  message: FALSE
---

## Setup

```{r, echo=FALSE,message=FALSE,results='hide',eval=TRUE}
rm(list=ls())
set.seed(123)
devtools::load_all("../manydist/")
library(devtools)
library(tidyverse)
library(tidymodels)
library(cluster)
library(palmerpenguins)
```


## Data

```{r, eval=TRUE}
pengs = palmerpenguins::penguins |> na.omit()
method = c("euclidean_onehot","hl","hl_add","gower","gudmm","dkss","mod_gower","u_ind","u_dep", "u_dep_manh")

```




<!-- ##  KNN -->

<!-- ```{r, eval=TRUE} -->
<!-- # source("../manydist/R/make_mdist_recipe.R") -->
<!-- # source("../manydist/R/mdist_methods_info.R") -->


<!-- invalid_for_step_mdist <- c("gudmm", "dkss", "mod_gower") -->
<!-- valid_methods <- setdiff(method, invalid_for_step_mdist) -->


<!-- scenario_structure_w_params <- crossing(scenario_structure, method=valid_methods) |> -->
<!--   left_join(mdist_method_lookup, by = "method") -->



<!-- ``` -->

<!-- ### check that `mdist` and `step_mdist` provide the same results -->


<!-- ### Test to train distance computations -->

<!-- ```{r, eval=TRUE} -->
<!-- n_neighbors = round(sqrt(1000)) -->

<!-- workflow_structure = scenario_structure_w_params |> -->
<!--   mutate( -->
<!--     # This may already be a bit costly -->
<!--     init_split = purrr::map( -->
<!--       .x = df, -->
<!--       ~ initial_split(.x, prop = .75, strata = response), -->
<!--       .progress = TRUE   # progress here -->
<!--     ), -->

<!--     tr_df = purrr::map( -->
<!--       .x = init_split, -->
<!--       ~ training(.x), -->
<!--       .progress = TRUE   # and here -->
<!--     ), -->

<!--     preprocessing = purrr::pmap( -->
<!--       list(tr_df, mdist_type, mdist_preset, param_set), -->
<!--       ~ make_mdist_recipe( -->
<!--           df           = ..1, -->
<!--           mdist_type   = ..2, -->
<!--           mdist_preset = ..3, -->
<!--           param_set    = ..4, -->
<!--           outcome      = "response" -->
<!--         ), -->
<!--       .progress = TRUE   # building recipes can be slow -->
<!--     ), -->

<!--     prepped_rec = purrr::map( -->
<!--       .x = preprocessing, -->
<!--       ~ prep(.x), -->
<!--       .progress = TRUE -->
<!--     ) -->
<!--     ) -->
<!-- ``` -->

<!-- ### KNN predictions -->

<!-- ```{r, eval=TRUE} -->
<!-- workflow_structure = workflow_structure |> -->
<!--   mutate( -->
<!--     knn_spec = purrr::map( -->
<!--       .x = preprocessing, -->
<!--       ~ nearest_neighbor_dist( -->
<!--           mode      = "classification", -->
<!--           neighbors = n_neighbors -->
<!--         ) |> set_engine("precomputed"), -->
<!--       .progress = TRUE -->
<!--     ), -->

<!--     knn_wf = purrr::map2( -->
<!--       .x = preprocessing, -->
<!--       .y = knn_spec, -->
<!--       ~ workflow(preprocessor = .x, spec = .y), -->
<!--       .progress = TRUE -->
<!--     ), -->

<!--     # 🔴 This is usually the *really* heavy bit -->
<!--     test_fit = purrr::map2( -->
<!--       .x = init_split, -->
<!--       .y = knn_wf, -->
<!--       ~ .y |> last_fit(.x), -->
<!--       .progress = TRUE   # main progress bar here -->
<!--     ) -->
<!--     ) -->
<!-- ``` -->

<!-- ### collecting metrics -->

<!-- ```{r, eval=TRUE} -->
<!-- workflow_structure = workflow_structure |> -->
<!--   mutate( -->
<!--     metrics = purrr::map( -->
<!--       .x = test_fit, -->
<!--       ~ collect_metrics(.x), -->
<!--       .progress = TRUE -->
<!--     ) -->
<!--   ) -->

<!-- selected_results = workflow_structure |>  -->
<!--   dplyr::select(dominance, noise, method, metrics, rep) -->

<!-- results_name = paste0("wf_structure_", n_rep, "_rep.RData") -->
<!-- save(file = results_name, selected_results) -->


<!-- ``` -->

<!-- ```{r} -->
<!-- library(tidyverse) -->
<!-- load(file=results_name) -->

<!-- results_long <- selected_results |> dplyr::filter(method != "hl_add") |>  -->
<!--   tidyr::unnest(metrics) -->

<!-- results_accuracy <- results_long |> -->
<!--   dplyr::filter(.metric == "accuracy") -->

<!-- ``` -->
<!-- ```{r} -->
<!-- method_levels <- c("baseline", "naive", "hl", "hl_add", "gower", -->
<!--                    "gudmm", "dkps", "mod_gower", "u_ind", "u_dep", "u_dep_manh") -->


<!-- my_colors <- c( -->
<!--   # Set B -->
<!--   # "baseline"    = "#8c564b", -->
<!--   "naive"       = "#e377c2", -->
<!--   "hl"          = "#bcbd22", -->
<!--   # "gudmm"       = "#ff7f0e", -->
<!--   # "dkps"        = "#A9A9A9",  # dark grey -->

<!--   # Set A -->
<!--   "hl_add"      = "#1f77b4", -->
<!--   "u_ind"       = "#2ca02c", -->
<!--   "u_dep"       = "#d62728", -->
<!--   "u_dep_manh"       = "#d62728", -->
<!--   "gower"       = "#FFBF00" -->
<!--   # "mod_gower"   = "#9467bd" -->
<!-- ) -->

<!-- my_shapes <- c( -->
<!--   # "baseline"    = 16,  # filled circle -->
<!--   "naive"       = 17,  # filled triangle -->
<!--   "hl"          = 15,  # filled square -->
<!--   "hl_add"      = 3,   # plus -->
<!--   "gower"       = 4,   # cross -->
<!--   # "gudmm"       = 18,  # filled diamond -->
<!--   # "dkps"        = 8,   # star -->
<!--   # "mod_gower"   = 0,   # empty square -->
<!--   "u_ind"       = 1,   # empty circle -->
<!--   "u_dep"       = 2,    # empty triangle -->
<!--   "u_dep_manh"       = 10 -->
<!-- ) -->


<!-- knn_exp_plot=results_accuracy |> group_by(dominance, noise,method) |>  -->
<!--   ggplot(mapping=aes(x=method,y=.estimate, fill=method))+ -->
<!--   geom_boxplot()+facet_grid(noise~dominance)+ theme_bw()+ -->
<!--    theme(axis.text.x = element_text(angle = 60, hjust = 1))+ -->
<!--     theme(legend.position = "none")+ -->
<!--   ylab("accuracy") + xlab("methods")+ -->
<!--   scale_fill_manual(values = my_colors)  -->

<!-- plotname= paste0(results_name |> str_remove(".RData"),"_knn_plot.pdf") -->
<!-- ggsave(filename = plotname,knn_exp_plot,width=8,height = 4) -->

<!-- ``` -->


<!-- ### PAM experiment -->

<!-- ```{r} -->
<!-- scenario_structure_w_params_pam <- crossing(scenario_structure, method=method) |> -->
<!--   left_join(mdist_method_lookup, by = "method") |> dplyr::filter(rep<6) |> -->
<!--   mutate( -->
<!--     preprocessing = purrr::pmap( -->
<!--       list(df, mdist_type, mdist_preset, param_set), -->
<!--       ~ make_mdist_recipe( -->
<!--         df           = ..1, -->
<!--         mdist_type   = ..2, -->
<!--         mdist_preset = ..3, -->
<!--         param_set    = ..4, -->
<!--         outcome      = "response" -->
<!--       ), -->
<!--       .progress = TRUE   # building recipes can be slow -->
<!--     ), -->

<!--     prepped_rec = purrr::map( -->
<!--       .x = preprocessing, -->
<!--       ~ prep(.x), -->
<!--       .progress = TRUE -->
<!--     ) -->
<!--   ) -->



<!-- ``` -->

